using Microsoft.EntityFrameworkCore.Migrations;

namespace CleanArchitecture.Infrastructure.Persistence.Migrations
{
    public partial class ContriesSeed : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('AF','Afghanistan');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('AL','Albania');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('AG','Algeria');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('AQ','American Samoa');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('AN','Andorra');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('AO','Angola');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('AV','Anguilla');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('AY','Antarctica');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('AC','Antigua and Barbuda');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('AR','Argentina');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('AM','Armenia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('AA','Aruba');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('AS','Australia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('AU','Austria');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('AJ','Azerbaijan');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('BF','Bahamas');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('BA','Bahrain');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('BG','Bangladesh');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('BB','Barbados');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('BO','Belarus');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('BE','Belgium');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('BH','Belize');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('BN','Benin');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('BD','Bermuda');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('BT','Bhutan');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('BL','Bolivia (Plurinational State of)');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('NL','Bonaire, Sint Eustatius and Saba');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('BK','Bosnia and Herzegovina');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('BC','Botswana');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('BV','Bouvet Island');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('BR','Brazil');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('IO','British Indian Ocean Territory');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('VI','British Virgin Islands');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('BX','Brunei Darussalam');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('BU','Bulgaria');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('UV','Burkina Faso');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('BY','Burundi');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('CV','Cabo Verde');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('CB','Cambodia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('CM','Cameroon');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('CA','Canada');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('CJ','Cayman Islands');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('CT','Central African Republic');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('CD','Chad');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('CI','Chile');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('CH','China');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('HK','China, Hong Kong Special Administrative Region');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('MC','China, Macao Special Administrative Region');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('KT','Christmas Island');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('CK','Cocos (Keeling) Islands');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('CO','Colombia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('CN','Comoros');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('CF','Congo');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('CW','Cook Islands');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('CS','Costa Rica');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('HR','Croatia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('CU','Cuba');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('UC','Curaçao');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('CY','Cyprus');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('EZ','Czechia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('IV','Côte d''Ivoire');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('KN','Democratic People''s Republic of Korea');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('CG','Democratic Republic of the Congo');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('DA','Denmark');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('DJ','Djibouti');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('DO','Dominica');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('DR','Dominican Republic');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('EC','Ecuador');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('EG','Egypt');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('ES','El Salvador');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('EK','Equatorial Guinea');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('ER','Eritrea');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('EN','Estonia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('WZ','Eswatini');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('ET','Ethiopia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('FK','Falkland Islands (Malvinas)');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('FO','Faroe Islands');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('FJ','Fiji');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('FI','Finland');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('FR','France');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('FG','French Guiana');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('FP','French Polynesia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('FS','French Southern Territories');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('GB','Gabon');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('GA','Gambia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('GG','Georgia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('GM','Germany');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('GH','Ghana');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('GI','Gibraltar');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('GR','Greece');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('GL','Greenland');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('GJ','Grenada');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('GP','Guadeloupe');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('GQ','Guam');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('GT','Guatemala');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('GK','Guernsey');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('GV','Guinea');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('PU','Guinea-Bissau');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('GY','Guyana');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('HA','Haiti');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('HM','Heard Island and McDonald Islands');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('VT','Holy See');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('HO','Honduras');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('HU','Hungary');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('IC','Iceland');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('IN','India');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('ID','Indonesia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('IR','Iran (Islamic Republic of)');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('IZ','Iraq');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('EI','Ireland');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('IM','Isle of Man');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('IS','Israel');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('IT','Italy');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('JM','Jamaica');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('JA','Japan');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('JE','Jersey');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('JO','Jordan');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('KZ','Kazakhstan');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('KE','Kenya');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('KR','Kiribati');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('KU','Kuwait');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('KG','Kyrgyzstan');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('LA','Lao People''s Democratic Republic');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('LG','Latvia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('LE','Lebanon');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('LT','Lesotho');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('LI','Liberia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('LY','Libya');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('LS','Liechtenstein');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('LH','Lithuania');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('LU','Luxembourg');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('MA','Madagascar');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('MI','Malawi');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('MY','Malaysia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('MV','Maldives');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('ML','Mali');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('MT','Malta');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('RM','Marshall Islands');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('MB','Martinique');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('MR','Mauritania');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('MP','Mauritius');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('MF','Mayotte');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('MX','Mexico');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('FM','Micronesia (Federated States of)');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('MN','Monaco');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('MG','Mongolia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('MJ','Montenegro');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('MH','Montserrat');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('MO','Morocco');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('MZ','Mozambique');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('BM','Myanmar');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('WA','Namibia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('NR','Nauru');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('NP','Nepal');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('NL','Netherlands');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('NC','New Caledonia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('NZ','New Zealand');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('NU','Nicaragua');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('NG','Niger');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('NI','Nigeria');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('NE','Niue');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('NF','Norfolk Island');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('CQ','Northern Mariana Islands');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('NO','Norway');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('MU','Oman');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('PK','Pakistan');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('PS','Palau');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('PM','Panama');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('PP','Papua New Guinea');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('PA','Paraguay');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('PE','Peru');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('RP','Philippines');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('PC','Pitcairn');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('PL','Poland');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('PO','Portugal');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('RQ','Puerto Rico');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('QA','Qatar');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('KS','Republic of Korea');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('MD','Republic of Moldova');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('RO','Romania');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('RS','Russian Federation');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('RW','Rwanda');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('RE','Réunion');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('TB','Saint Barthélemy');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('SH','Saint Helena');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('SC','Saint Kitts and Nevis');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('ST','Saint Lucia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('RN','Saint Martin (French Part)');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('SB','Saint Pierre and Miquelon');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('VC','Saint Vincent and the Grenadines');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('WS','Samoa');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('SM','San Marino');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('TP','Sao Tome and Principe');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES (NULL,'Sark');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('SA','Saudi Arabia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('SG','Senegal');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('RI,KV','Serbia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('SE','Seychelles');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('SL','Sierra Leone');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('SN','Singapore');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('NN','Sint Maarten (Dutch part)');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('LO','Slovakia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('SI','Slovenia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('BP','Solomon Islands');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('SO','Somalia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('SF','South Africa');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('SX','South Georgia and the South Sandwich Islands');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('OD','South Sudan');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('SP','Spain');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('CE','Sri Lanka');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('GZ,WE','State of Palestine');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('SU','Sudan');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('NS','Suriname');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('SV,JN','Svalbard and Jan Mayen Islands');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('SW','Sweden');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('SZ','Switzerland');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('SY','Syrian Arab Republic');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('TI','Tajikistan');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('TH','Thailand');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('MK','The former Yugoslav Republic of Macedonia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('TT','Timor-Leste');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('TO','Togo');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('TL','Tokelau');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('TN','Tonga');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('TD','Trinidad and Tobago');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('TS','Tunisia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('TU','Turkey');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('TX','Turkmenistan');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('TK','Turks and Caicos Islands');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('TV','Tuvalu');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('UG','Uganda');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('UP','Ukraine');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('AE','United Arab Emirates');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('UK','United Kingdom of Great Britain and Northern Ireland');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('TZ','United Republic of Tanzania');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('FQ,HQ,DQ,JQ,KQ,MQ,BQ,LQ,WQ','United States Minor Outlying Islands');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('VQ','United States Virgin Islands');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('US','United States of America');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('UY','Uruguay');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('UZ','Uzbekistan');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('NH','Vanuatu');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('VE','Venezuela (Bolivarian Republic of)');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('VM','Viet Nam');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('WF','Wallis and Futuna Islands');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('WI','Western Sahara');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('YM','Yemen');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('ZA','Zambia');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES ('ZI','Zimbabwe');
INSERT INTO Countries(TwoLetterCode,EnglishName) VALUES (NULL,'Åland Islands');
");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("TRUNCATE TABLE Countries");
        }
    }
}
