import React from 'react';
import styles from './styles.module.scss';

const CharterTos = () => {
    return <div className={styles.container}><p className={styles.title}>GENERAL TERMS AND CONDITIONS</p>
        <p><strong>&nbsp;</strong></p>
        <p><strong>Article 1</strong></p>
        <p><strong>Introductory provisions</strong></p>
        <p>(1) The General Terms and Conditions provided herein shall regulate your use of this Website and our services as the Agency and the legal relationship between the Service Provider and you as the Agency.</p>
        <p>(2) All of the provisions of these General Terms and Conditions shall be fully binding. As the Agency, by registering to, accessing and using the Website, you unequivocally agree to and accept to be bound by these General Terms and Conditions, which you acknowledge you have read, understood and accepted in their entirety.</p>
        <p>&nbsp;</p>
        <p><strong>Article 2</strong></p>
        <p><strong>Definitions of expressions</strong></p>
        <p>(1) In these General Terms and Conditions, the subsequent expressions shall have the following meanings:</p>
        <ol>
            <li>a) Service Provider: The Service Provider is BRAIN INFORMATION TECHNOLOGIES d.o.o., Ulica Baruna Trenka 10., OIB: 40269256588</li>
            <li>b) Guest: The Guest is a natural or legal person of full legal and contractual capacity who uses the Website and the services of the Service Provider for the purposes of Booking a Skipper.</li>
            <li>c) Agency: The Agency is a natural or legal person of full legal and contractual capacity who is either the owner of a Vessel, or has obtained legal authorization by the respective owner of the Vessel for its use and/or rent, or is acting as an agent for the respective owner or user of the Vessel for the purposes of its further use and/or rent, and has as such obtained the right from the Service Provider to use the Website.</li>
            <li>d) Skipper: The Skipper is a natural person that possesses the knowledge, skills and the required documentary authorization to operate Vessels, who may be authorized by a particular Agency to operate a particular Vessel of that Agency and may be selected by the Guest for that purpose.</li>
            <li>e) List of Skippers: List of Skippers is a list containing information about Skippers who are available, capable and authorized by a particular Agency to operate particular Vessels of that Agency in particular time periods.</li>
            <li>f) Vessel: Vessels are boats, sailboats, catamarans, motorboats, yachts, jet skis and any other kind of sea, lake or river vessels of a particular Agency.</li>
            <li>g) Booking: Booking is the reservation made by the Guest of a Skipper from the List of Skippers, for the purpose of operating a particular Vessel of a particular Agency for a particular time period.</li>
            <li>h) Website: Website is the Website of the Service Provider, located at <a href="https://www.skipper.agency">https://www.skipper.agency</a> </li>
        </ol>
        <p>&nbsp;</p>
        <p><strong>Article 3</strong></p>
        <p><strong>Services of the Service Provider</strong></p>
        <p>(1) The Service Provider shall provide the Agency with a list of potential Skippers from which the Agency may at its sole discretion choose certain Skippers for the purposes of operating their Vessels that the Guests previously independently booked with the Agency for a certain time period. Depending on the Agency's choices, Skippers may be organized within the Agency's profile into separate lists of Skippers who are pending, approved or declined the Agency's confirmation to operate their particular Vessels. Skippers who were approved by the Agency to operate a particular Vessel shall be displayed on the List of Skippers for that Vessel.</p>
        <p>(2) The Service Provider is not the owner, user, lessor and/or manager of Vessels of Agencies. The Service Provider does not act as an organiser, agent, manager and/or representative of Agencies and their respective Vessels.</p>
        <p>(3) The Service Provider does not act as an employer, agent, manager and/or representative of Skippers.</p>
        <p>(4) The Service Provider does not act as an agent, organiser and/or representative of Guests and/or any other passengers for which the Guest booked a Vessel with the particular Agency.</p>
        <p>&nbsp;</p>
        <p><strong>Article 4</strong></p>
        <p><strong>Obligations of the Agency</strong></p>
        <p>(1) The Agency shall create their online profile on the Website. The Agency's online profile shall contain information that includes, but is not necessarily limited to the Agency's name or company name, number, producers and descriptions of Vessels that they own or are authorized to use, time periods for which they provide their Vessels to the Guest, indiciation of fees etc.</p>
        <p>(2) The Agency shall choose and communicate to the Service Provider a certain number of Skippers who the Agency shall authorize to operate particular Vessels of that Agency for particular time periods.</p>
        <p>(3) The Agency shall arrange separate agreements with both the Guests and the Skippers pertaining to the details regarding booking of Skippers who will operate the booked Vessels (e.g. the payment of Skippers, cancellation etc.), in which the terms and conditions of the Agency&rsquo;s services shall be established. The Service Provider shall not be a party in these agreements and shall not be bound by their Terms and Conditions or any other provisions which regulate the legal relationship between the Agency and the Guest, as well as provisions which regulate the legal relationship between the Agency and the Skipper.</p>
        <p>(4) The Agency declares that all of its services with regard to the Website and the Booking shall be practiced by employees or agents of the Agency that have the required technical and professional skills.</p>
        <p>(5) The Booking of a Skipper, as well as all technical and financial details in connection with such a Booking, is processed between the Agency and the Skipper and/or the Agency and the Guest under the terms and conditions of the Agency. The Service Provider assumes no liability for such transactions. The Service Provider, if requested, shall receive, notify and forward to each Agency any requests or enquiries made through the Website by a Guest. The Service Provider shall not act in any way as a contracting agent or representative for the Agency, or as a broker or insurer in each case, in relation to the transactions of the Agency which the Agency concludes with Guests and Skippers through the Website.</p>
        <p>(6) The Agency shall, upon the request of the Service Provider, supply the Service Provider with the evidence of ownership or possession of the Vessel or a proof of legal authorization to rent such a Vessel, as well as that all licenses and authorizations in respect of the Vessel have been orderly issued and received.</p>
        <p>(7) The Agency shall have the liability to receive and keep in force any license and other authorizations required by any applicable law for the Vessels. The Agency is obliged to provide the Service Provider with such licenses and authorizations immediately upon the Service Provider&rsquo;s request. The Service Provider will not be obliged to perform any services to a particular Agency, if that Agency does not provide the Service Provider the required documents proving the proper ownership and/or possession and use of a particular Vessel or a properly signed Agency party (where this is obligatory).</p>
        <p>(8) The Agency explicitly guarantees, declares and undertakes that:</p>
        <ol>
            <li>a) the Agency is the lawful owner of the Vessel and that it has good and saleable title to the Vessel and/or it has been duly authorized to use the Vessel and/or it has received an exclusive unconditional right for the use and provision of the Vessels;</li>
            <li>b) the Agency has received all required licenses, insurances, permissions and any other documents and requisites for the use of the Vessel;</li>
            <li>c) the licenses, permissions, insurances and other documents and requisites laid down in Article 4, paragraph (8), point b) of these General Terms and Conditions, shall be valid during the entire period of use of the Agency's services by the Guest, as well as during the period these General Terms and Conditions are in force;</li>
            <li>d) any picture, photo, icon, drawing, text, logo, graphic, image and/or indication of fees uploaded by the Agency on the Website related with the Vessels accurately and entirely correlates to the particular Vessels;</li>
            <li>e) the Agency has a considerable knowledge of and expertise in providing his services to the Guests and maintains a high quality of infrastructure while performing its services;</li>
            <li>f) the Agency has one or more active insurance policies with a reputable insurance firm to cover any obligations that may occur with the usage of the Agency's services or under this agreement and such insurance policies shall be valid during the entire period of use of the Agency's services by the Guest, as well as during the period these General Terms and Conditions are in force;</li>
            <li>g) the Agency has not breached or violated any law or regulation the breach of which has or might reasonably be expected to have a negative material effect on the Website and the Service Provider;</li>
            <li>h) there are no claims and no investigations being conducted against the Agency or any subsidiary or affiliates that have or might reasonably be expected to have a material disadvantageous effect on the Agency, Skipper, Guest and/or the Service Provider;</li>
            <li>i) in performing its services, the Agency shall act with increased care in accordance with professional rules and practice, i.e. the Agency shall exercise the care of a good expert.</li>
        </ol>
        <p>&nbsp;</p>
        <p><strong>Article 5</strong></p>
        <p><strong>The Booking of a Skipper</strong></p>
        <p>(1) After the Guest independently booked a Vessel with a particular Agency, the Guest may request to book an available Skipper through the Website.</p>
        <p>(2) All legal and financial rights and obligations of the Agency towards the Guest, as well as the obligations of the Guest towards the Agency are regulated by the contractual relationship between the Guest and the Agency whose Vessel the Guest previously booked with that Agency.</p>
        <p>(3) All legal and financial rights and obligations of the Agency towards the Skipper, as well as the obligations of the Skipper towards the Agency are regulated by the contractual relationship between the Agency and the Skipper whom the Agency authorized to operate a particular Vessel.</p>
        <p>(4) When a Guest makes a Booking of a Skipper through the Website, the Agency acknowledges and understands that the legal relationship regulating each specific Booking is between each individual Agency and each particular Guest and that the Agency shall refer to and shall be bound by the terms and conditions that will apply to that Booking in relation to payment, cancellation and all other related matters.&nbsp;</p>
        <p>(5) The Service Provider shall not be a party in the legal relationship between the Guest and the Agency and shall not be bound by any contractual provisions and/or terms and conditions stipulated between the Guest and the Agency.</p>
        <p>(6) The Service Provider shall not be a party in the legal relationship between the Skipper and the Agency and shall not be bound by any contractual provisions and/or terms and conditions stipulated between the Skipper and the Agency.</p>
        <p>(7) The Agency shall ensure that after a Guest has independently booked a Vessel for a certain time period, they may provide to the Guest a Skipper who will operate the Vessel. For the aforementioned purpose, the Agency shall determine in advance the potential Skippers who may operate their Vessels. When the Guest books a particular Vessel for a particular time period independently with the Agency, the Agency shall provide the Guest with a URL (Uniform Resource Locator) link to the Website, where the List of Skippers shall be displayed for that particular Vessel. &nbsp;The Service Provider does not determine the available Skippers for a particular Vessel and it does not subject Skippers to an additional process of evaluation of their expertise. The Service Provider merely provides the Agency with a list of available Skippers which the Agencies may then select at their sole full discretion to be available for operating their particular Vessels.</p>
        <p>(8) After the Guest requests to book a specific Skipper from the List of Skippers for a particular Vessel, the Service Provider shall notify the Guest within 48 hours of such request on the confirmation of the particular Skipper to operate the particular Vessel with regard to the Guest's Booking. If the Skipper does not respond in the provided time period, or declines to operate the particular Vessel for the particular time period, the Service Provider shall notify the Guest on the unavailability of the Skipper, after which the Guest may request to book a different Skipper from the List of Skippers for a particular Vessel. If none of the Skippers available on the Website for a particular Vessel approves the Guest's request, the Agency shall communicate directly with the Guest for the purposes of obtaining a Skipper.</p>
        <p>(9) The Agency agrees that they are solely responsible for determining their own tax reporting requirements with regard to a respective Booking and the operation of the respective Vessel. The Service Provider does not provide any legal advice thereto.</p>
        <p>&nbsp;</p>
        <p><strong>Article 6</strong></p>
        <p><strong>Payment</strong></p>
        <p>(1) The Service Provider provides the use of the Website and its services free of charge for the Agency.</p>
        <p>(2) Details pertaining to payment of the Booking are regulated by the legal relationship between the Agency and the Guest, as well as the legal relationship between the Agency and the Skipper, for which the Service Provider accepts no legal and financial responsibility.</p>
        <p>&nbsp;</p>
        <p><strong>Article 7</strong></p>
        <p><strong>Limitation of liability and indemnity</strong></p>
        <p>(1) The Agency explicitly acknowledges, understands and accepts that the Website and the Service Provider's services are provided on an &lsquo;as is&rsquo; basis, i.e. without representations or warranties of any kind, and the information contained on the Website is for general information purposes only and subject to change without prior notice.</p>
        <p>(2) The Agency explicitly acknowledges, understands and accepts that the Service Provider, or the Service Provider's authorized officers, employees, agents or representatives shall not be held liable by the Agency for any direct, indirect or consequential expense, loss, damage, liability or any other harmful consequences suffered by the Agency that arose or may arise as a result of actions or omissions with regard to the Agency's use of the Website and the performance of the Agency's obligations regarding the operation of their Vessels which include, but are not limited to:</p>
        <ol>
            <li>a) non-performance, partial performance, or the lack of exact and compliant performance of the Agency's services;</li>
            <li>b) non-performance, partial performance, or the lack of exact and compliant performance of the Skipper's services;</li>
            <li>c) non-performance, partial performance, or the lack of exact and compliant performance of the Guest's obligations;</li>
            <li>c) completeness, accuracy, representation and veracity of all information provided to the Service Provider by the Agencies and/or the Skippers that is posted on the Website, including but not limited to Skippers' fees, rates, availability, cancellation and change policies, Vessel descriptions, levels and ratings of the Agencies' and Skippers' quality and levels and ratings of the Skippers' expertise;</li>
            <li>d) the non-existence or invalidity of titles, licenses, insurances, permissions and authorizations required to use Vessels and perform services of the Agency and/or the Skipper;</li>
            <li>e) the violation of any law or regulation by the Agency and/or the Skipper, which has or might reasonably be expected to have a negative material effect on the Website, the Service Provider and the use of the Website by the Agency, the Skipper and/or the Guest;</li>
            <li>f) any physical or immaterial damage suffered due to the misconduct of the Agency, the Guest and/or the Skipper for the duration of use of the Vessel.</li>
        </ol>
        <p>(4) The Agency explicitly acknowledges, understands and accepts that any expense, loss, damage, liability or other harmful consequence suffered by the Agency that arose or may arise as a result of actions or omissions with regard to the Agency's use of the Website and the performance of their obligations regarding the operation of their Vessels, shall be borne by the respective Agency, Guest and/or Skipper, in accordance with the legal relationship between the Guest and the Agency, as well as the legal relationship between the Skipper and the Agency, and other legal provisions applicable to those legal relationships.</p>
        <p>(5) The Agency shall indemnify and keep indemnified the Service Provider and all of its officers, employees, agents and representatives promptly on a full indemnity basis from and against all claims, demands, actions, suits, proceedings, orders, losses, damages, costs and expenses and any and all other liabilites of whatsoever nature, which the Service Provider may sustain or incur, whether actual or contingent, directy or indirectly, in connection with the obligations of the Agency provided by these General Terms and Conditions.</p>
        <p>&nbsp;</p>
        <p><strong>Article 8</strong></p>
        <p><strong>Cancellation policy and changes</strong></p>
        <p>(1) The Agency who decides to change or cancel the operation of the Vessel which the Guest previously independently booked with that Agency, or receives a request for a change or cancellation from the Guest and/or Skipper, shall immediately contact and communicate with the Guest and/or Skipper and shall also notify the Service Provider.</p>
        <p>(2) Any cancellations and/or changes in the Bookings, as well as potential supplementary charges and other damage arising due to such cancellations and changes are exclusively regulated by the legal relationship between the Agency and the particular Guest and/or Skipper.</p>
        <p>&nbsp;</p>
        <p><strong>Article 9</strong></p>
        <p><strong>Legal and contractual capacity and unauthorized use</strong></p>
        <p>(1) The Agency declares that they possess full legal and contractual capacity and that they shall be responsible for any contractual and/or financial liabilities that may occur as a result of use of the Website.</p>
        <p>(2) The Agency acknowledges that they are legally and financially responsible for all use of this Website and/or those using their login username and password. The Service Provider must be informed and contacted immediately, if the Agency has lost or has noticed that an unauthorized person may have access to the login name and/or password. The Service Provider shall not be held liable for any damage arising from unauthorized use of the Website by a person different from the Agency, if the Agency failed to immediately inform the Service Provider of such potentially unauthorized use.</p>
        <p>&nbsp;</p>
        <p><strong>Article 10</strong></p>
        <p><strong>Final Provisions</strong></p>
        <p>(1) The Service Provider is obliged to provide protection of the personal data that the Service Provider collects of a Agency that is not a legal person, as well as the personal data of Agencies' employees and/or agents. &nbsp;The Service Provider's Privacy Policy is an integral part of these General Terms and Conditions, and by accepting the General Terms and Conditions, the Agency also accepts the Service Provider's Privacy Policy.</p>
        <p>(2) The Service Provider owns all intellectual property rights and materials contained on the Website. The Service Provider grants to the Agency a non-transferable, limited, revocable and non-exclusive license for their use of the Website. The Agency may not copy, reproduce, modify, publish, upload, download, post transmit or distribute any part of the Website in any way without the written permission of the Service Provider.</p>
        <p>(3) The Service Provider retains the right to subsequently modify these General Terms and Conditions. Any such changes shall be communicated to the Agency without undue delay and shall enter into force after 5 days from the day of their publishing on the Website. The Agency that does not agree to the modified General Terms and Conditions shall immediately contact the Service Provider for the purpose of terminating the legal relationship between the Agency and the Service Provider.</p>
        <p>(4) The Service Provider retains the right to post additional guidelines and rules on the Website with regard to the Agency's use thereof and to these General Terms and Conditions. By using the Website, the Agency accepts to be bound by these General Terms and Conditions and additionally published guidelines and rules which pertain to them.</p>
        <p>(5) These General Terms and Conditions and the legal relationship between the Service Provider and the Agency shall be exclusively governed by and construed in accordance with the laws of the Republic of Croatia. Any disputes arising out or in connection with these General Terms and Conditions shall exclusively be submitted to resolution by the competent court in Rijeka, the Republic of Croatia.</p>
        <p>(6) These General Terms and Conditions shall be published on the Website and shall enter into force on 1 March 2020.</p>
        <p>&nbsp;</p>
    </div >
}

export default CharterTos;